import { useParams } from 'react-router-dom';
import { Badge, Card, Disclaimer } from '../../components/ui';

const pages: Record<string,{title:string;subtitle:string;sections:Array<{heading:string;body:string}>}>={
  terms:{title:'Điều khoản sử dụng',subtitle:'Quy tắc sử dụng nền tảng Sandbox.',sections:[{heading:'Phạm vi dịch vụ',body:'BTC BigData Platform cung cấp dữ liệu, mô phỏng giao dịch và công cụ phân tích phục vụ học tập, nghiên cứu và trình diễn công nghệ.'},{heading:'Trách nhiệm người dùng',body:'Người dùng tự chịu trách nhiệm bảo vệ tài khoản, kiểm tra timestamp dữ liệu và không sử dụng kết quả mô phỏng như cam kết lợi nhuận hoặc chỉ dẫn đầu tư.'},{heading:'Giới hạn trách nhiệm',body:'Nền tảng không vận hành sàn giao dịch thật, không nhận tiền gửi, không lưu ký tài sản và không chịu trách nhiệm cho quyết định tài chính bên ngoài môi trường Sandbox.'}]},
  privacy:{title:'Chính sách quyền riêng tư',subtitle:'Nguyên tắc thu thập và sử dụng dữ liệu.',sections:[{heading:'Dữ liệu tài khoản',body:'Email, tên hiển thị, trạng thái gói và lịch sử mô phỏng được lưu để xác thực và cung cấp chức năng tương ứng.'},{heading:'Bảo mật',body:'Phiên xác thực sử dụng Supabase Auth. Frontend không lưu khóa service-role hoặc khóa AI. Dữ liệu nhạy cảm không được chia sẻ với nhà quảng cáo.'},{heading:'Quyền của người dùng',body:'Người dùng có thể cập nhật hồ sơ, đổi mật khẩu, đăng xuất và liên hệ quản trị viên để yêu cầu hỗ trợ dữ liệu.'}]},
  compliance:{title:'Tuân thủ Sandbox & AML/KYC',subtitle:'Nguyên tắc thiết kế an toàn cho môi trường mô phỏng.',sections:[{heading:'Sandbox only',body:'Toàn bộ số dư, giao dịch BTC và Premium trong hệ thống là dữ liệu demo, trừ khi backend được cấu hình riêng với cổng thanh toán Sandbox.'},{heading:'AML/KYC theo nguyên tắc',body:'Nền tảng không thay thế quy trình KYC/AML của tổ chức tài chính. Phần này chỉ mô tả nhận thức tuân thủ trong phạm vi học phần.'},{heading:'Không lưu ký',body:'Hệ thống không giữ private key, seed phrase, tiền pháp định hoặc tài sản số thật của người dùng.'}]},
  risk:{title:'Công bố rủi ro',subtitle:'Các giới hạn khi sử dụng dữ liệu và AI.',sections:[{heading:'Biến động thị trường',body:'Bitcoin có mức biến động cao. Dữ liệu lịch sử và chỉ báo kỹ thuật không bảo đảm kết quả trong tương lai.'},{heading:'Rủi ro dữ liệu',body:'Nguồn API bên thứ ba có thể chậm, thiếu hoặc gián đoạn. Luôn kiểm tra độ mới và nguồn dữ liệu.'},{heading:'Rủi ro AI',body:'AI có thể tạo diễn giải chưa chính xác. Câu trả lời chỉ dùng để tham khảo và không thay thế tư vấn chuyên môn.'}]},
  disclaimer:{title:'Miễn trừ trách nhiệm',subtitle:'Thông tin quan trọng trước khi sử dụng nền tảng.',sections:[{heading:'Không phải tư vấn',body:'Mọi dữ liệu, thuế ước tính, Decision Hub và AI Advisor không phải tư vấn đầu tư, thuế hoặc pháp lý.'},{heading:'Không cam kết',body:'Nền tảng không cam kết tính liên tục, độ chính xác tuyệt đối hoặc lợi nhuận từ bất kỳ tín hiệu nào.'},{heading:'Mục đích học thuật',body:'Sản phẩm được xây dựng cho môn Công nghệ dịch vụ tài chính và mục đích trình diễn kỹ thuật.'}]},
};
export default function LegalPage(){const{slug='terms'}=useParams();const page=pages[slug]||pages.terms;return <div className="page-enter mx-auto max-w-4xl space-y-5"><header className="legal-hero"><Badge variant="gold">Legal & Compliance</Badge><h1>{page.title}</h1><p>{page.subtitle}</p></header><div className="space-y-4">{page.sections.map((section,index)=><Card key={section.heading} className="card-reveal p-6" style={{animationDelay:`${index*60}ms`}}><div className="flex gap-4"><span className="legal-number">{String(index+1).padStart(2,'0')}</span><div><h2 className="text-lg font-semibold">{section.heading}</h2><p className="mt-2 text-sm leading-7 text-[var(--text-sec)]">{section.body}</p></div></div></Card>)}</div><Disclaimer text="Tài liệu này mô tả nguyên tắc vận hành của sản phẩm học thuật, không thay thế văn bản pháp lý hoặc tư vấn của chuyên gia."/></div>}
