from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware

from app.config import get_settings
from app.routers import market, news, settlement, tax

settings = get_settings()

app = FastAPI(
    title=f"{settings.app_name} Data API",
    version=settings.api_version,
    description=(
        "Server dữ liệu riêng cho BTC BigData Platform. "
        "Chỉ phục vụ market data/news/tax/settlement để giảm tải backend chính."
    ),
)

app.add_middleware(GZipMiddleware, minimum_size=500, compresslevel=5)


@app.get("/")
def root():
    return {
        "name": f"{settings.app_name} Data API",
        "version": settings.api_version,
        "docs": "/docs",
        "health": "/health",
        "role": "data-server",
        "endpoints": [
            "/api/overview?hours=72",
            "/api/latest",
            "/api/ohlcv?hours=168",
            "/api/indicators/summary",
            "/api/p2p-spread?hours=168",
            "/api/data-status",
            "/api/data-reliability",
            "/api/risk-score",
            "/api/market-alerts",
            "/api/p2p-comparison",
            "/api/news/latest",
            "/api/tax-estimate?amount=100000000&country=VN",
            "/api/net-settlement?amount=100000000&unit=vnd&side=sell&price_source=p2p",
        ],
    }


@app.get("/health")
def health():
    return {"status": "ok", "environment": settings.app_env, "role": "data-server"}


app.include_router(market.router)
app.include_router(news.router)
app.include_router(tax.router)
app.include_router(settlement.router)

# Wrap the complete ASGI application with CORSMiddleware.  Using CORS as the
# outermost layer guarantees Access-Control-Allow-Origin is also present on
# responses generated by unhandled exceptions; otherwise the browser can hide
# a real backend 500 behind a misleading "blocked by CORS" message.
app = CORSMiddleware(
    app=app,
    allow_origins=settings.cors_origin_list,
    allow_origin_regex=settings.cors_origin_regex,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
    allow_headers=["*"],
    expose_headers=["Content-Length", "Content-Encoding", "X-Request-ID"],
    max_age=86400,
)

