from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware

from app.config import get_settings
from app.routers import admin, ai, alerts, auth_status, demo_trades, market, news, payment, settlement, tax, wallet

settings = get_settings()

app = FastAPI(
    title=settings.app_name,
    version=settings.api_version,
    description="Backend FastAPI cho BTC BigData AI Advisor: Supabase + AI Advisor + API dữ liệu tài chính.",
)

app.add_middleware(GZipMiddleware, minimum_size=500, compresslevel=5)


@app.get("/")
def root():
    return {
        "name": settings.app_name,
        "version": settings.api_version,
        "docs": "/docs",
        "health": "/health",
        "endpoints": [
            "/api/overview?hours=72",
            "/api/latest",
            "/api/ohlcv?hours=168",
            "/api/indicators/summary",
            "/api/p2p-spread?hours=168",
            "/api/tax-estimate?amount=100000000&country=VN",
            "/api/net-settlement?amount=100000000&unit=vnd&side=sell&price_source=p2p",
            "/api/data-status",
            "/api/data-reliability",
            "/api/risk-score",
            "/api/market-alerts",
            "/api/p2p-comparison",
            "/api/news/latest",
            "/api/ai/ask",
            "/api/ai/history?limit=24",
            "/api/wallet/me",
            "/api/demo-trades/terminal?hours=168&limit=20",
            "/api/wallet/topup/create",
            "/api/admin/dashboard",
            "/api/admin/users",
        ],
    }


@app.get("/health")
def health():
    return {"status": "ok", "environment": settings.app_env}


app.include_router(auth_status.router)
app.include_router(market.router)
app.include_router(news.router)
app.include_router(tax.router)
app.include_router(settlement.router)
app.include_router(ai.router)
app.include_router(demo_trades.router)
app.include_router(alerts.router)
app.include_router(payment.router)
app.include_router(wallet.router)
app.include_router(admin.router)

# Wrap the complete ASGI application with CORSMiddleware.  Using CORS as the
# outermost layer guarantees Access-Control-Allow-Origin is also present on
# responses generated by unhandled exceptions; otherwise the browser can hide
# a real backend 500 behind a misleading "blocked by CORS" message.
app = CORSMiddleware(
    app=app,
    allow_origins=settings.cors_origin_list,
    allow_origin_regex=settings.cors_origin_regex,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
    allow_headers=["*"],
    expose_headers=["Content-Length", "Content-Encoding", "X-Request-ID"],
    max_age=86400,
)

