import { useEffect, useMemo, useState } from 'react';
import { apiRequest, clearApiCache } from '../../lib/api';
import { formatDateTime, formatNumber, formatVND } from '../../lib/format';
import { Badge, Button, Card, Input, Modal, Select, Skeleton } from '../../components/ui';
import { useDebouncedValue } from '../../hooks/useDebouncedValue';
import { useToast } from '../../context/ToastContext';

type UserRow = Record<string, unknown>;
type UsersPayload = { users?: { data?: UserRow[]; page?: number; page_size?: number; total?: number; has_next?: boolean } };
export default function AdminUsers(){
 const [data,setData]=useState<UsersPayload|null>(null),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[plan,setPlan]=useState('all'),[limit,setLimit]=useState('20'),[page,setPage]=useState(1),[selected,setSelected]=useState<UserRow|null>(null),[pending,setPending]=useState<UserRow|null>(null),[busy,setBusy]=useState(false); const q=useDebouncedValue(search,350); const {showToast}=useToast();
 const path=useMemo(()=>`/api/admin/users?page=${page}&limit=${limit}&search=${encodeURIComponent(q)}&status=${status}&plan=${plan}`,[page,limit,q,status,plan]);
 const load=async(force=false)=>{setLoading(true);try{setData(await apiRequest<UsersPayload>(path,{force}));}catch(e){showToast(e instanceof Error?e.message:'Không tải được người dùng.','error');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[path]);
 useEffect(()=>{setPage(1)},[q,status,plan,limit]);
 const users=data?.users; const rows=users?.data||[];
 const toggleStatus=async()=>{if(!pending?.user_id)return;setBusy(true);const next=String(pending.status)==='suspended'?'active':'suspended';try{await apiRequest(`/api/admin/users/${pending.user_id}/status`,{method:'PATCH',body:{status:next},cacheTtl:0});clearApiCache();setPending(null);await load(true);showToast(next==='active'?'Đã mở khóa tài khoản.':'Đã tạm khóa tài khoản.','success');}catch(e){showToast(e instanceof Error?e.message:'Không cập nhật được trạng thái.','error');}finally{setBusy(false)}};
 return <div className="page-enter space-y-5"><header><Badge variant="gold">User Management</Badge><h1 className="mt-2 text-2xl font-extrabold">Quản lý người dùng</h1><p className="mt-1 text-sm text-[var(--text-sec)]">Tìm kiếm và lọc trên server; mỗi trang chỉ tải số dòng cần thiết.</p></header>
 <Card className="p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Input placeholder="Tìm tên hoặc email..." prefix="⌕" value={search} onChange={e=>setSearch(e.target.value)}/><Select value={status} onChange={setStatus} options={[{value:'all',label:'Tất cả trạng thái'},{value:'active',label:'Đang hoạt động'},{value:'suspended',label:'Tạm khóa'}]}/><Select value={plan} onChange={setPlan} options={[{value:'all',label:'Tất cả gói'},{value:'premium',label:'Premium'},{value:'free',label:'Free'}]}/><Select value={limit} onChange={setLimit} options={[{value:'20',label:'20 dòng / trang'},{value:'30',label:'30 dòng / trang'},{value:'50',label:'50 dòng / trang'}]}/></div></Card>
 <Card className="overflow-hidden">{loading?<div className="space-y-2 p-5">{Array.from({length:6}).map((_,i)=><Skeleton key={i} className="h-14"/>)}</div>:<div className="table-scroll"><table className="data-table"><thead><tr><th>Người dùng</th><th>Vai trò</th><th>Gói</th><th>Số dư ví</th><th>Giao dịch</th><th>Hoạt động gần nhất</th><th>Trạng thái</th><th></th></tr></thead><tbody>{rows.length?rows.map((u,i)=><tr key={String(u.user_id||i)}><td><button className="flex items-center gap-3 text-left" onClick={()=>setSelected(u)}><span className="avatar-lazy">{String(u.full_name||u.email||'U').slice(0,1).toUpperCase()}</span><span><strong className="block max-w-52 truncate text-sm">{String(u.full_name||'Chưa đặt tên')}</strong><small className="block max-w-52 truncate text-[var(--text-sec)]">{String(u.email||'')}</small></span></button></td><td><Badge variant={String(u.role)==='admin'?'violet':'neutral'}>{String(u.role||'user')}</Badge></td><td><Badge variant={u.premium_active?'gold':'neutral'}>{u.premium_active?'Premium':'Free'}</Badge></td><td className="tabular">{formatVND(u.wallet_balance_vnd)}</td><td>{formatNumber(u.trade_count,0)}</td><td>{formatDateTime(u.last_login_at)}</td><td><Badge variant={String(u.status)==='suspended'?'danger':'success'} pulse={String(u.status)!=='suspended'}>{String(u.status||'active')}</Badge></td><td><Button size="sm" variant={String(u.status)==='suspended'?'secondary':'danger'} onClick={()=>setPending(u)}>{String(u.status)==='suspended'?'Mở khóa':'Tạm khóa'}</Button></td></tr>):<tr><td colSpan={8} className="py-12 text-center text-[var(--text-sec)]">Không tìm thấy người dùng.</td></tr>}</tbody></table></div>}<div className="flex items-center justify-between border-t border-[var(--border-soft)] p-4"><Button size="sm" variant="secondary" disabled={page<=1||loading} onClick={()=>setPage(p=>Math.max(1,p-1))}>← Trang trước</Button><span className="text-xs text-[var(--text-sec)]">Trang {users?.page||page}{users?.total?` · ${formatNumber(users.total,0)} người dùng`:''}</span><Button size="sm" variant="secondary" disabled={!users?.has_next||loading} onClick={()=>setPage(p=>p+1)}>Trang tiếp →</Button></div></Card>
 <Modal open={Boolean(selected)} onClose={()=>setSelected(null)} title="Chi tiết người dùng">{selected&&<div className="grid gap-3 sm:grid-cols-2"><div className="metric-box"><span>Họ tên</span><strong>{String(selected.full_name||'—')}</strong></div><div className="metric-box"><span>Email</span><strong className="break-all text-sm">{String(selected.email||'—')}</strong></div><div className="metric-box"><span>Ngày tạo</span><strong className="text-sm">{formatDateTime(selected.created_at)}</strong></div><div className="metric-box"><span>Gói</span><strong>{selected.premium_active?'Premium':'Free'}</strong></div><div className="metric-box"><span>Số dư</span><strong>{formatVND(selected.wallet_balance_vnd)}</strong></div><div className="metric-box"><span>Số giao dịch</span><strong>{formatNumber(selected.trade_count,0)}</strong></div></div>}</Modal>
 <Modal open={Boolean(pending)} onClose={()=>setPending(null)} title={String(pending?.status)==='suspended'?'Mở khóa người dùng':'Tạm khóa người dùng'} footer={<><Button variant="secondary" onClick={()=>setPending(null)}>Hủy</Button><Button variant={String(pending?.status)==='suspended'?'primary':'danger'} loading={busy} onClick={()=>void toggleStatus()}>Xác nhận</Button></>}><p className="text-sm text-[var(--text-sec)]">Thao tác áp dụng cho <strong className="text-[var(--text-main)]">{String(pending?.email||'tài khoản')}</strong>. Backend đồng bộ trạng thái profile và Supabase Auth.</p></Modal></div>;
}
