import { useEffect, useMemo, useState } from 'react';
import { apiRequest } from '../../lib/api';
import { formatDateTime, formatVND } from '../../lib/format';
import { Badge, Button, Card, Input, Modal, Select, Skeleton } from '../../components/ui';
import { useDebouncedValue } from '../../hooks/useDebouncedValue';
import { useToast } from '../../context/ToastContext';

type Activity = Record<string, unknown>;
type Payload = { activity_page?: { data?: Activity[]; page?: number; page_size?: number; total?: number; has_next?: boolean } };
const statusVariant = (value: unknown): 'success' | 'danger' | 'warning' | 'neutral' => { const s = String(value || '').toLowerCase(); return s === 'success' || s === 'completed' || s === 'buy' ? 'success' : s === 'failed' || s === 'sell' ? 'danger' : s === 'pending' ? 'warning' : 'neutral'; };
export default function AdminTransactions(){
 const [data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[type,setType]=useState('all'),[status,setStatus]=useState('all'),[dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState(''),[sort,setSort]=useState('desc'),[limit,setLimit]=useState('20'),[page,setPage]=useState(1),[selected,setSelected]=useState<Activity|null>(null);const q=useDebouncedValue(search,350);const {showToast}=useToast();
 const path=useMemo(()=>{const p=new URLSearchParams({page:String(page),limit,type,status,search:q,sort});if(dateFrom)p.set('date_from',dateFrom);if(dateTo)p.set('date_to',dateTo);return `/api/admin/activity?${p}`},[page,limit,type,status,q,sort,dateFrom,dateTo]);
 useEffect(()=>{const c=new AbortController();setLoading(true);apiRequest<Payload>(path,{force:true,cacheTtl:0,signal:c.signal}).then(setData).catch(e=>{if(!c.signal.aborted)showToast(e instanceof Error?e.message:'Không tải được hoạt động.','error')}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[path]);
 useEffect(()=>{setPage(1)},[limit,type,status,q,sort,dateFrom,dateTo]); const pg=data?.activity_page;const rows=pg?.data||[];
 const reset=()=>{setSearch('');setType('all');setStatus('all');setDateFrom('');setDateTo('');setSort('desc');setPage(1)};
 return <div className="page-enter space-y-5"><header><Badge variant="gold">Audit & Billing</Badge><h1 className="mt-2 text-2xl font-extrabold">Giao dịch & Premium</h1><p className="mt-1 text-sm text-[var(--text-sec)]">Lọc và phân trang hoạt động giao dịch demo, thanh toán Premium và AI Advisor.</p></header>
 <Card className="p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Input placeholder="Email, ID, hoạt động..." prefix="⌕" value={search} onChange={e=>setSearch(e.target.value)}/><Select value={type} onChange={setType} options={[{value:'all',label:'Tất cả loại'},{value:'trade',label:'Giao dịch demo'},{value:'premium',label:'Premium Sandbox'},{value:'ai',label:'AI Advisor'}]}/><Select value={status} onChange={setStatus} options={[{value:'all',label:'Tất cả trạng thái'},{value:'success',label:'Thành công'},{value:'pending',label:'Đang chờ'},{value:'failed',label:'Thất bại'},{value:'completed',label:'Đã hoàn tất'},{value:'buy',label:'AI BUY'},{value:'sell',label:'AI SELL'},{value:'neutral',label:'AI NEUTRAL'}]}/><Select value={limit} onChange={setLimit} options={[{value:'10',label:'10 dòng / trang'},{value:'20',label:'20 dòng / trang'},{value:'50',label:'50 dòng / trang'}]}/><Input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/><Input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)}/><Select value={sort} onChange={setSort} options={[{value:'desc',label:'Mới nhất trước'},{value:'asc',label:'Cũ nhất trước'}]}/><Button variant="secondary" onClick={reset}>Xóa bộ lọc</Button></div></Card>
 <Card className="overflow-hidden">{loading?<div className="space-y-2 p-5">{Array.from({length:7}).map((_,i)=><Skeleton key={i} className="h-14"/>)}</div>:<div className="table-scroll"><table className="data-table"><thead><tr><th>Hoạt động</th><th>Người dùng</th><th>Loại</th><th>Giá trị</th><th>Trạng thái</th><th>Thời gian</th><th></th></tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={String(r.id||i)}><td><strong className="text-sm">{String(r.title||'Hoạt động')}</strong></td><td className="max-w-52 truncate">{String(r.detail||'—')}</td><td><Badge variant={String(r.type)==='premium'?'gold':String(r.type)==='ai'?'violet':'info'}>{String(r.type||'—')}</Badge></td><td className="tabular font-semibold">{r.amount_vnd?formatVND(r.amount_vnd):'—'}</td><td><Badge variant={statusVariant(r.status)}>{String(r.status||'—')}</Badge></td><td>{formatDateTime(r.created_at)}</td><td><Button size="sm" variant="secondary" onClick={()=>setSelected(r)}>Chi tiết</Button></td></tr>):<tr><td colSpan={7} className="py-12 text-center text-[var(--text-sec)]">Không có hoạt động phù hợp.</td></tr>}</tbody></table></div>}<div className="flex items-center justify-between border-t border-[var(--border-soft)] p-4"><Button size="sm" variant="secondary" disabled={page<=1||loading} onClick={()=>setPage(p=>Math.max(1,p-1))}>← Trang trước</Button><span className="text-xs text-[var(--text-sec)]">Trang {pg?.page||page}{pg?.total!=null?` · ${pg.total} bản ghi`:''}</span><Button size="sm" variant="secondary" disabled={!pg?.has_next||loading} onClick={()=>setPage(p=>p+1)}>Trang tiếp →</Button></div></Card>
 <Modal open={Boolean(selected)} onClose={()=>setSelected(null)} title="Chi tiết hoạt động">{selected&&<div className="grid gap-3 sm:grid-cols-2">{Object.entries(selected).map(([key,value])=><div key={key} className="metric-box"><span>{key}</span><strong className="break-all text-sm">{key.includes('at')?formatDateTime(value):key.includes('amount')?formatVND(value):String(value??'—')}</strong></div>)}</div>}</Modal></div>;
}
