import { Badge, Card, Disclaimer } from '../../components/ui';

type Section='theory'|'business'|'experiment'|'guide'|'about';
const content:Record<Section,{title:string;sub:string;items:Array<{title:string;body:string;tags:string[]}>}>={
 theory:{title:'Lý thuyết Công nghệ dịch vụ tài chính',sub:'Liên hệ kiến thức học phần với BTC BigData Platform.',items:[{title:'Big Data trong thị trường Bitcoin',body:'Pipeline thu thập OHLCV, P2P và tin tức tạo dữ liệu đa nguồn, theo thời gian, phục vụ chỉ báo và phân tích.',tags:['Volume','Velocity','Variety']},{title:'AI Advisor',body:'AI nhận ngữ cảnh từ dữ liệu backend, giải thích chỉ báo và rủi ro bằng ngôn ngữ dễ hiểu thay vì tự động giao dịch.',tags:['Explainable AI','Risk']},{title:'FinTech Sandbox',body:'Môi trường mô phỏng giúp kiểm thử quy trình ví, Premium và giao dịch mà không phát sinh tiền thật.',tags:['Sandbox','Compliance']}]},
 business:{title:'Business Model Canvas',sub:'Mô hình kinh doanh cho nền tảng phân tích Bitcoin tại Việt Nam.',items:[{title:'Giá trị cung cấp',body:'Một màn hình tổng hợp giá, P2P, thuế, thực nhận, cảnh báo và AI hỗ trợ ra quyết định.',tags:['Value Proposition']},{title:'Khách hàng mục tiêu',body:'Người học FinTech, nhà đầu tư mới và nhóm nghiên cứu cần công cụ mô phỏng dễ trình bày.',tags:['Customer Segments']},{title:'Doanh thu',body:'Premium Sandbox 49.000đ/tháng, affiliate, quảng cáo FinTech và API dữ liệu trong tương lai.',tags:['Revenue Streams']}]},
 experiment:{title:'Thử nghiệm API & dữ liệu',sub:'Các kịch bản kiểm chứng chức năng của project.',items:[{title:'Market Overview',body:'Kiểm tra endpoint tổng hợp trả giá, OHLCV, P2P, risk và alerts trong một payload.',tags:['GET /api/overview']},{title:'Virtual Trade',body:'Nạp ví demo, xem trước lệnh BUY/SELL và kiểm tra thay đổi portfolio.',tags:['POST /api/demo-trades']},{title:'Data Reliability',body:'So sánh timestamp mới nhất với ngưỡng freshness và kiểm tra fallback/cache.',tags:['Observability']}]},
 guide:{title:'Hướng dẫn đọc chỉ báo',sub:'Ý nghĩa các chỉ báo đang dùng trong nền tảng.',items:[{title:'RSI 14',body:'RSI trên 70 thường được xem là vùng quá mua, dưới 30 là quá bán; cần kết hợp xu hướng và volume.',tags:['Momentum']},{title:'MACD',body:'MACD histogram dương thể hiện động lượng tăng, âm thể hiện động lượng giảm; giao cắt không bảo đảm xu hướng.',tags:['Trend']},{title:'EMA & Bollinger',body:'EMA mô tả xu hướng theo nhiều khung; Bollinger Bands mô tả biên độ biến động quanh đường trung bình.',tags:['Volatility']}]},
 about:{title:'Về BTC BigData Platform',sub:'Bitcoin Sandbox · FinTech Analytics · AI Advisor.',items:[{title:'Mục tiêu',body:'Xây dựng sản phẩm chạy được, có dữ liệu thật/fallback, giao diện chuyên nghiệp và phù hợp phạm vi học phần.',tags:['Education','Demo']},{title:'Kiến trúc',body:'React + Vite frontend, FastAPI backend, Supabase PostgreSQL/Auth và pipeline đồng bộ dữ liệu.',tags:['Full Stack']},{title:'Nguyên tắc',body:'Minh bạch nguồn dữ liệu, tách Sandbox khỏi giao dịch thật và luôn hiển thị cảnh báo rủi ro.',tags:['Trust','Safety']}]}
};
export default function CourseContent({section}:{section:Section}){const page=content[section];return <div className="page-enter space-y-5"><header><Badge variant="violet">Course Knowledge</Badge><h1 className="mt-2 text-2xl font-extrabold">{page.title}</h1><p className="mt-1 text-sm text-[var(--text-sec)]">{page.sub}</p></header><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{page.items.map((item,index)=><Card key={item.title} className="card-reveal p-6" style={{animationDelay:`${index*60}ms`}}><span className="text-3xl text-[#F7931A]">{index===0?'₿':index===1?'✦':'◈'}</span><h2 className="mt-4 text-lg font-semibold">{item.title}</h2><p className="mt-2 text-sm leading-7 text-[var(--text-sec)]">{item.body}</p><div className="mt-5 flex flex-wrap gap-2">{item.tags.map(tag=><Badge key={tag} variant="neutral">{tag}</Badge>)}</div></Card>)}</section><Disclaimer text="Nội dung học thuật được trình bày ngắn gọn để hỗ trợ thuyết trình; khi làm báo cáo cần trích dẫn tài liệu môn học và nguồn chính thức." tone="info"/></div>}
